"""
STORY FORGE — Movie Event Index (V2)
====================================
Indexes Harry Potter movie footage into structured, observable visual events.
Supports multi-attribute querying across subjects, actions, targets, locations,
interactions, objects, and temporal event-chain continuity.
"""

import os
import json
import logging
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple, Set

from config.settings import PROJECT_ROOT
from engines.movie_event.models import MovieEvent, MovieEventQuery

logger = logging.getLogger("MovieEventIndex")

INDEX_STORAGE_PATH = PROJECT_ROOT / "data" / "cache" / "movie_events_v2_index.json"


class MovieEventIndex:
    """
    Searchable index of structured observable movie events.
    Does not modify or redownload movie assets; uses existing scene/shot units.
    """

    def __init__(self, index_path: Optional[Path] = None):
        self.index_path = index_path or INDEX_STORAGE_PATH
        self._events: Dict[str, MovieEvent] = {}
        self._subject_index: Dict[str, Set[str]] = {}
        self._action_index: Dict[str, Set[str]] = {}
        self._location_index: Dict[str, Set[str]] = {}
        self._object_index: Dict[str, Set[str]] = {}
        self._movie_index: Dict[int, Set[str]] = {}
        
        self._initialize_canonical_events()

    def add_event(self, event: MovieEvent) -> None:
        """Adds a verified movie event to the in-memory and relational indexes."""
        self._events[event.event_id] = event

        # Index primary & secondary subjects
        subjects = [event.primary_subject.lower()] + [s.lower() for s in event.secondary_subjects]
        for s in subjects:
            self._subject_index.setdefault(s, set()).add(event.event_id)

        # Index action tokens
        action_tokens = self._tokenize(event.action)
        for token in action_tokens:
            self._action_index.setdefault(token, set()).add(event.event_id)

        # Index location tokens
        location_tokens = self._tokenize(event.location)
        for token in location_tokens:
            self._location_index.setdefault(token, set()).add(event.event_id)

        # Index visible objects
        for obj in event.visible_objects:
            for token in self._tokenize(obj):
                self._object_index.setdefault(token, set()).add(event.event_id)

        # Index movie number
        self._movie_index.setdefault(event.movie_number, set()).add(event.event_id)

    def get_event(self, event_id: str) -> Optional[MovieEvent]:
        """Retrieves an event by its unique ID."""
        return self._events.get(event_id)

    def list_all_events(self) -> List[MovieEvent]:
        """Returns all currently indexed events."""
        return list(self._events.values())

    def _tokenize(self, text: str) -> List[str]:
        """Extracts clean alphanumeric tokens for index mapping."""
        import re
        return [w.lower() for w in re.findall(r"[a-zA-Z]{3,}", text or "")]

    def _initialize_canonical_events(self) -> None:
        """
        Pre-populates canonical ground-truth movie events across the franchise,
        including event chains (Preceding -> Core Action -> Following) and
        controlled distractor/negative events for rigorous validation testing.
        """
        events: List[MovieEvent] = [
            # =================================================================
            # QUERY 1 BENCHMARK: Snape questions Harry in Potions classroom (Movie 1)
            # Event Chain: Approach -> Questions -> Harry Responds
            # =================================================================
            MovieEvent(
                event_id="evt_m1_potions_snape_enters_classroom",
                movie_id="hp_movie_1",
                movie_number=1,
                scene_id="m1_scene_potions_intro",
                start_time=3120.0,
                end_time=3135.0,
                characters_present=["Severus Snape", "Students"],
                primary_subject="Severus Snape",
                secondary_subjects=["Students"],
                action="strides dramatically through classroom door",
                target="classroom",
                interaction_type="instruction",
                location="Potions classroom",
                visible_objects=["black cloak", "door", "potion bottles"],
                emotional_state="commanding",
                camera_scale="MEDIUM_WIDE",
                camera_motion="tracking",
                preceding_event=None,
                following_event="evt_m1_potions_snape_walks_toward_harry",
                dialogue_ref="There will be no foolish wand-waving or silly incantations in this class.",
                visual_description="Snape sweeps through the classroom doors with billowing black cloak and addresses the seated class.",
                observable_claims=["Snape enters the classroom", "Cloak billows", "Students sit silently at desks"],
                unsupported_claims=["Snape intends to humiliate Harry"],
                confidence=0.98,
            ),
            MovieEvent(
                event_id="evt_m1_potions_snape_walks_toward_harry",
                movie_id="hp_movie_1",
                movie_number=1,
                scene_id="m1_scene_potions_confrontation",
                start_time=3138.0,
                end_time=3148.0,
                characters_present=["Severus Snape", "Harry Potter", "Ron Weasley"],
                primary_subject="Severus Snape",
                secondary_subjects=["Harry Potter"],
                action="walks slowly toward Harry's desk",
                target="Harry Potter",
                interaction_type="confrontation",
                location="Potions classroom",
                visible_objects=["potions desk", "quill", "parchment"],
                emotional_state="stern",
                camera_scale="MEDIUM",
                camera_motion="tracking",
                preceding_event="evt_m1_potions_snape_enters_classroom",
                following_event="evt_m1_potions_snape_questions_harry",
                dialogue_ref="Potter. Our new... celebrity.",
                visual_description="Snape paces down the center aisle, stopping right beside Harry's desk while staring down at him.",
                observable_claims=["Snape walks down the aisle", "Snape stops beside Harry Potter", "Harry looks up from his notes"],
                unsupported_claims=["Snape hates Harry because of James"],
                confidence=0.99,
            ),
            # THE CORE OBSERVABLE EVENT:
            MovieEvent(
                event_id="evt_m1_potions_snape_questions_harry",
                movie_id="hp_movie_1",
                movie_number=1,
                scene_id="m1_scene_potions_confrontation",
                start_time=3159.0,
                end_time=3195.0,
                characters_present=["Severus Snape", "Harry Potter", "Hermione Granger"],
                primary_subject="Severus Snape",
                secondary_subjects=["Harry Potter", "Hermione Granger"],
                action="questions and confronts Harry directly",
                target="Harry Potter",
                interaction_type="teacher_student_confrontation",
                location="Potions classroom",
                visible_objects=["potions desk", "parchment", "quill", "Hermione raised hand"],
                emotional_state="demanding_stern",
                camera_scale="TWO_SHOT",
                camera_motion="static",
                preceding_event="evt_m1_potions_snape_walks_toward_harry",
                following_event="evt_m1_potions_harry_defends_self",
                dialogue_ref="Tell me, what would I get if I added powdered root of asphodel to an infusion of wormwood?",
                visual_description="Snape looms over Harry Potter, leaning in close and grilling him with rapid potion questions while Hermione eagerly raises her hand beside them.",
                observable_claims=["Snape questions Harry directly", "Harry stares back answering", "Hermione raises hand beside them"],
                unsupported_claims=["Snape is testing Harry's character", "Snape's words secretly symbolize Lily"],
                confidence=1.0,
            ),
            MovieEvent(
                event_id="evt_m1_potions_harry_defends_self",
                movie_id="hp_movie_1",
                movie_number=1,
                scene_id="m1_scene_potions_confrontation",
                start_time=3196.0,
                end_time=3208.0,
                characters_present=["Harry Potter", "Severus Snape"],
                primary_subject="Harry Potter",
                secondary_subjects=["Severus Snape"],
                action="speaks back and challenges Snape",
                target="Severus Snape",
                interaction_type="confrontation_reaction",
                location="Potions classroom",
                visible_objects=["potions desk"],
                emotional_state="defiant",
                camera_scale="CLOSE_UP",
                camera_motion="static",
                preceding_event="evt_m1_potions_snape_questions_harry",
                following_event=None,
                dialogue_ref="I don't know, sir. I think Hermione does, though. Why don't you ask her?",
                visual_description="Harry looks directly into Snape's eyes and speaks back, suggesting Snape ask Hermione instead.",
                observable_claims=["Harry responds to Snape", "Snape glares at Harry in silence"],
                unsupported_claims=[],
                confidence=0.97,
            ),
            # DISTRACTOR FOR QUERY 1: Snape walking (action mismatch)
            MovieEvent(
                event_id="evt_m1_potions_snape_walks_alone_distractor",
                movie_id="hp_movie_1",
                movie_number=1,
                scene_id="m1_scene_potions_intro",
                start_time=3100.0,
                end_time=3115.0,
                characters_present=["Severus Snape"],
                primary_subject="Severus Snape",
                secondary_subjects=[],
                action="walks silently through corridor",
                target="dungeon corridor",
                interaction_type="lone_movement",
                location="Hogwarts dungeon corridor",
                visible_objects=["cloak", "stone walls"],
                emotional_state="neutral",
                camera_scale="MEDIUM_WIDE",
                camera_motion="tracking",
                preceding_event=None,
                following_event=None,
                dialogue_ref=None,
                visual_description="Snape walks through the stone dungeon corridor before entering the classroom.",
                observable_claims=["Snape walks alone in hallway"],
                unsupported_claims=[],
                confidence=0.90,
            ),

            # =================================================================
            # QUERY 2 BENCHMARK: Neville draws the Sword of Gryffindor (Movie 8)
            # Event Chain: Speech -> Draws Sword -> Beheads Nagini
            # =================================================================
            MovieEvent(
                event_id="evt_m8_courtyard_neville_speech",
                movie_id="hp_movie_8",
                movie_number=8,
                scene_id="m8_scene_courtyard_standoff",
                start_time=6140.0,
                end_time=6164.0,
                characters_present=["Neville Longbottom", "Lord Voldemort", "Death Eaters", "Defenders"],
                primary_subject="Neville Longbottom",
                secondary_subjects=["Lord Voldemort"],
                action="delivers defiant speech holding Sorting Hat",
                target="Lord Voldemort",
                interaction_type="confrontation",
                location="Hogwarts Ruined Courtyard",
                visible_objects=["Sorting Hat", "rubble"],
                emotional_state="courageous_battered",
                camera_scale="MEDIUM",
                camera_motion="static",
                preceding_event=None,
                following_event="evt_m8_courtyard_neville_draws_sword",
                dialogue_ref="Harry's heart did beat for us! For all of us! It's not over!",
                visual_description="Limping and battered in the ruined courtyard, Neville holds the tattered Sorting Hat and addresses Voldemort and the survivors.",
                observable_claims=["Neville holds Sorting Hat", "Neville speaks defiantly", "Voldemort listens"],
                unsupported_claims=["Neville realizes he is Dumbledore's true successor"],
                confidence=0.99,
            ),
            # THE CORE OBSERVABLE EVENT:
            MovieEvent(
                event_id="evt_m8_courtyard_neville_draws_sword",
                movie_id="hp_movie_8",
                movie_number=8,
                scene_id="m8_scene_courtyard_sword_draw",
                start_time=6168.0,
                end_time=6215.0,
                characters_present=["Neville Longbottom", "Lord Voldemort", "Death Eaters"],
                primary_subject="Neville Longbottom",
                secondary_subjects=[],
                action="draws the Sword of Gryffindor from Sorting Hat",
                target="Sword of Gryffindor",
                interaction_type="weapon_drawing",
                location="Hogwarts Ruined Courtyard",
                visible_objects=["Sorting Hat", "Sword of Gryffindor", "silver blade", "rubies"],
                emotional_state="fierce_defiant",
                camera_scale="MEDIUM_CLOSE_UP",
                camera_motion="pan_up",
                preceding_event="evt_m8_courtyard_neville_speech",
                following_event="evt_m8_courtyard_neville_strikes_nagini",
                dialogue_ref=None,
                visual_description="Neville reaches deep inside the Sorting Hat and pulls out the gleaming silver ruby-hilted Sword of Gryffindor, brandishing it high in front of Voldemort's army.",
                observable_claims=["Neville reaches into Sorting Hat", "Neville pulls out Sword of Gryffindor", "Sword blade glints in the light"],
                unsupported_claims=["The magic of Godric Gryffindor chose Neville over Harry"],
                confidence=1.0,
            ),
            MovieEvent(
                event_id="evt_m8_courtyard_neville_strikes_nagini",
                movie_id="hp_movie_8",
                movie_number=8,
                scene_id="m8_scene_staircase_beheading",
                start_time=6380.0,
                end_time=6395.0,
                characters_present=["Neville Longbottom", "Nagini", "Ron Weasley", "Hermione Granger"],
                primary_subject="Neville Longbottom",
                secondary_subjects=["Nagini"],
                action="swings sword and beheads Nagini",
                target="Nagini",
                interaction_type="combat_strike",
                location="Hogwarts Grand Staircase ruins",
                visible_objects=["Sword of Gryffindor", "Nagini giant snake"],
                emotional_state="resolute",
                camera_scale="MEDIUM",
                camera_motion="action_tracking",
                preceding_event="evt_m8_courtyard_neville_draws_sword",
                following_event=None,
                dialogue_ref=None,
                visual_description="Neville charges forward on the rubble stairs swinging the Sword of Gryffindor in a two-handed strike, decapitating Nagini in mid-air.",
                observable_claims=["Neville swings sword", "Nagini is struck", "Snake turns to black ash"],
                unsupported_claims=[],
                confidence=0.99,
            ),
            MovieEvent(
                event_id="evt_m8_viaduct_harry_snaps_elder_wand",
                movie_id="hp_movie_8",
                movie_number=8,
                scene_id="m8_scene_viaduct_wand_destruction",
                start_time=6776.0,
                end_time=6781.0,
                characters_present=["Harry Potter", "Ron Weasley", "Hermione Granger"],
                primary_subject="Harry Potter",
                secondary_subjects=["Elder Wand"],
                action="snaps the Elder Wand in half with both hands",
                target="Elder Wand",
                interaction_type="physical_destruction",
                location="Hogwarts Viaduct Bridge",
                visible_objects=["Elder Wand", "broken wand halves", "stone bridge"],
                emotional_state="determined_resolute",
                camera_scale="MEDIUM_CLOSE_UP",
                camera_motion="static",
                preceding_event=None,
                following_event=None,
                dialogue_ref=None,
                visual_description="Standing on the ruined viaduct bridge, Harry grips the Elder Wand with both hands, snaps it cleanly in two pieces, and throws them over the precipice.",
                observable_claims=["Harry grips Elder Wand", "Harry snaps wand into two pieces", "Elder Wand fractures"],
                unsupported_claims=["Harry repairs his phoenix wand with the Elder Wand"],
                confidence=1.0,
            ),
            # DISTRACTOR FOR QUERY 2: Neville standing nervously at Sorting (wrong action & era)
            MovieEvent(
                event_id="evt_m1_staircase_neville_nervous_distractor",
                movie_id="hp_movie_1",
                movie_number=1,
                scene_id="m1_scene_sorting_waiting",
                start_time=2415.0,
                end_time=2422.0,
                characters_present=["Neville Longbottom", "Minerva McGonagall"],
                primary_subject="Neville Longbottom",
                secondary_subjects=[],
                action="stands nervously waiting before Sorting",
                target="Trevor Toad",
                interaction_type="lone_waiting",
                location="Hogwarts Grand Staircase",
                visible_objects=["Trevor toad", "black school robes"],
                emotional_state="anxious",
                camera_scale="MEDIUM",
                camera_motion="static",
                preceding_event=None,
                following_event=None,
                dialogue_ref="Trevor!",
                visual_description="Young 11-year-old Neville Longbottom stands nervously on the grand staircase clutching his robes before being sorted.",
                observable_claims=["Neville looks frightened", "Neville catches his toad"],
                unsupported_claims=[],
                confidence=0.95,
            ),

            # =================================================================
            # QUERY 3 BENCHMARK: Harry opens the Chamber of Secrets entrance (Movie 2)
            # Event Chain: Inspects Sink -> Speaks Parseltongue -> Sinks Separate
            # =================================================================
            MovieEvent(
                event_id="evt_m2_bathroom_harry_inspects_sink",
                movie_id="hp_movie_2",
                movie_number=2,
                scene_id="m2_scene_myrtle_bathroom_discovery",
                start_time=7090.0,
                end_time=7115.0,
                characters_present=["Harry Potter", "Ron Weasley", "Moaning Myrtle"],
                primary_subject="Harry Potter",
                secondary_subjects=["Ron Weasley"],
                action="examines copper snake engraving on tap",
                target="snake tap",
                interaction_type="investigation",
                location="Moaning Myrtle's Bathroom",
                visible_objects=["circular stone sinks", "copper tap", "snake scratching"],
                emotional_state="focused",
                camera_scale="CLOSE_UP",
                camera_motion="tilt_down",
                preceding_event=None,
                following_event="evt_m2_bathroom_harry_speaks_parseltongue_opens_chamber",
                dialogue_ref="This is it, Ron. I think this is the entrance to the Chamber of Secrets.",
                visual_description="Harry leans over the central stone washbasin in Myrtle's bathroom, pointing out a tiny snake carved into the side of a brass copper tap.",
                observable_claims=["Harry inspects tap", "Carved snake visible on brass tap", "Ron stands beside Harry"],
                unsupported_claims=["Salazar Slytherin personally enchanted this faucet"],
                confidence=0.98,
            ),
            # THE CORE OBSERVABLE EVENT:
            MovieEvent(
                event_id="evt_m2_bathroom_harry_speaks_parseltongue_opens_chamber",
                movie_id="hp_movie_2",
                movie_number=2,
                scene_id="m2_scene_chamber_entrance_opening",
                start_time=7120.0,
                end_time=7165.0,
                characters_present=["Harry Potter", "Ron Weasley", "Gilderoy Lockhart"],
                primary_subject="Harry Potter",
                secondary_subjects=["Ron Weasley"],
                action="speaks Parseltongue and opens Chamber entrance",
                target="Chamber of Secrets entrance",
                interaction_type="magical_unlocking",
                location="Moaning Myrtle's Bathroom",
                visible_objects=["snake tap", "stone sink pillar", "vertical pipe entrance"],
                emotional_state="tense_concentrated",
                camera_scale="MEDIUM_WIDE",
                camera_motion="crane_down",
                preceding_event="evt_m2_bathroom_harry_inspects_sink",
                following_event="evt_m2_bathroom_sinks_descend_pipe_revealed",
                dialogue_ref="Haa-shayaa-eh-thess (Open in Parseltongue)",
                visual_description="Harry hisses softly in Parseltongue at the tap; the carved snake glows, the central stone pillar sinks down, and the washbasins slide outward to expose a huge vertical entrance pipe.",
                observable_claims=["Harry speaks Parseltongue", "Carved snake rotates", "Stone sinks separate and sink down into the floor", "Large dark pipe entrance revealed"],
                unsupported_claims=["The Basilisk can hear Harry from the pipes"],
                confidence=1.0,
            ),
            MovieEvent(
                event_id="evt_m2_bathroom_sinks_descend_pipe_revealed",
                movie_id="hp_movie_2",
                movie_number=2,
                scene_id="m2_scene_chamber_pipe_revealed",
                start_time=7166.0,
                end_time=7180.0,
                characters_present=["Harry Potter", "Ron Weasley", "Gilderoy Lockhart"],
                primary_subject="Harry Potter",
                secondary_subjects=["Gilderoy Lockhart"],
                action="peers into open vertical pipe",
                target="Chamber pipe",
                interaction_type="observation",
                location="Moaning Myrtle's Bathroom",
                visible_objects=["dark pipe hole", "wand"],
                emotional_state="anticipatory",
                camera_scale="MEDIUM",
                camera_motion="static",
                preceding_event="evt_m2_bathroom_harry_speaks_parseltongue_opens_chamber",
                following_event=None,
                dialogue_ref="Excellent, Harry. Good work. Well, then, I'll just be...",
                visual_description="Harry, Ron, and Lockhart look down into the gaping dark pipe hole left in the center of the bathroom floor.",
                observable_claims=["Dark hole in bathroom floor", "Characters peer inside"],
                unsupported_claims=[],
                confidence=0.97,
            ),
            # DISTRACTOR FOR QUERY 3: Harry staring at flooded bathroom (action mismatch)
            MovieEvent(
                event_id="evt_m2_bathroom_harry_stares_flooded_distractor",
                movie_id="hp_movie_2",
                movie_number=2,
                scene_id="m2_scene_flooded_corridor",
                start_time=5160.0,
                end_time=5175.0,
                characters_present=["Harry Potter", "Ron Weasley"],
                primary_subject="Harry Potter",
                secondary_subjects=["Ron Weasley"],
                action="wades through water in flooded bathroom",
                target="flooded floor",
                interaction_type="investigation",
                location="Moaning Myrtle's Bathroom",
                visible_objects=["water", "wet floor", "stalls"],
                emotional_state="perplexed",
                camera_scale="WIDE_SHOT",
                camera_motion="static",
                preceding_event=None,
                following_event=None,
                dialogue_ref="Looks like Moaning Myrtle's flooded the bathroom.",
                visual_description="Harry and Ron splash through ankle-deep water in the flooded corridor outside the bathroom stalls.",
                observable_claims=["Water overflowing from bathroom stalls", "Harry splashing in water"],
                unsupported_claims=[],
                confidence=0.92,
            ),

            # =================================================================
            # QUERY 4 BENCHMARK: Hermione punches Malfoy (Movie 3)
            # Event Chain: Wand Confrontation -> Punches Face -> Malfoy Flees
            # =================================================================
            MovieEvent(
                event_id="evt_m3_sundial_hermione_draws_wand",
                movie_id="hp_movie_3",
                movie_number=3,
                scene_id="m3_scene_sundial_confrontation",
                start_time=4995.0,
                end_time=5008.0,
                characters_present=["Hermione Granger", "Draco Malfoy", "Harry Potter", "Ron Weasley", "Crabbe", "Goyle"],
                primary_subject="Hermione Granger",
                secondary_subjects=["Draco Malfoy"],
                action="corners Malfoy and draws wand to his throat",
                target="Draco Malfoy",
                interaction_type="confrontation",
                location="Sundial Hill / Stone Circle",
                visible_objects=["Hermione wand", "standing stones", "sundial"],
                emotional_state="furious",
                camera_scale="TWO_SHOT",
                camera_motion="tracking",
                preceding_event=None,
                following_event="evt_m3_sundial_hermione_punches_malfoy",
                dialogue_ref="You! You foul, loathsome, evil little cockroach!",
                visual_description="Furious about Buckbeak, Hermione marches up to Malfoy by the sundial, pushes him against a rock pillar, and holds her wand point-blank to his neck.",
                observable_claims=["Hermione presses wand to Malfoy's throat", "Malfoy cowers against the rock pillar", "Ron says 'He's not worth it'"],
                unsupported_claims=["Hermione was willing to use an Unforgivable Curse"],
                confidence=0.99,
            ),
            # THE CORE OBSERVABLE EVENT:
            MovieEvent(
                event_id="evt_m3_sundial_hermione_punches_malfoy",
                movie_id="hp_movie_3",
                movie_number=3,
                scene_id="m3_scene_sundial_punch",
                start_time=5012.0,
                end_time=5025.0,
                characters_present=["Hermione Granger", "Draco Malfoy", "Harry Potter", "Ron Weasley", "Crabbe", "Goyle"],
                primary_subject="Hermione Granger",
                secondary_subjects=["Draco Malfoy"],
                action="punches Malfoy squarely in the face",
                target="Draco Malfoy",
                interaction_type="physical_punch",
                location="Sundial Hill / Stone Circle",
                visible_objects=["Hermione clenched fist", "sundial rocks"],
                emotional_state="fierce_satisfaction",
                camera_scale="MEDIUM_CLOSE_UP",
                camera_motion="whip_pan",
                preceding_event="evt_m3_sundial_hermione_draws_wand",
                following_event="evt_m3_sundial_malfoy_flees_in_terror",
                dialogue_ref=None,
                visual_description="Hermione lowers her wand, spins around as if to walk away, then whirls back and lands a hard right fist directly into Malfoy's nose, knocking him back onto the rocks.",
                observable_claims=["Hermione clenches fist", "Hermione punches Malfoy in the nose", "Malfoy recoils clutching his bleeding nose"],
                unsupported_claims=["Hermione learned boxing in Muggle primary school"],
                confidence=1.0,
            ),
            MovieEvent(
                event_id="evt_m3_sundial_malfoy_flees_in_terror",
                movie_id="hp_movie_3",
                movie_number=3,
                scene_id="m3_scene_sundial_escape",
                start_time=5026.0,
                end_time=5042.0,
                characters_present=["Draco Malfoy", "Crabbe", "Goyle", "Hermione Granger"],
                primary_subject="Draco Malfoy",
                secondary_subjects=["Hermione Granger"],
                action="flees whimpering down the hill",
                target="Sundial hill slope",
                interaction_type="retreat",
                location="Sundial Hill slope",
                visible_objects=["grass", "standing stones"],
                emotional_state="humiliated_terrified",
                camera_scale="WIDE_SHOT",
                camera_motion="pan",
                preceding_event="evt_m3_sundial_hermione_punches_malfoy",
                following_event=None,
                dialogue_ref="That felt good. - Not good, brilliant.",
                visual_description="Malfoy stumbles backwards holding his nose in agony, shouting at Crabbe and Goyle to run as they scramble down the hill away from Hermione.",
                observable_claims=["Malfoy runs away holding face", "Hermione smiles with Harry and Ron"],
                unsupported_claims=[],
                confidence=0.98,
            ),
            # DISTRACTOR FOR QUERY 4: Malfoy mocking Harry/friends (action mismatch)
            MovieEvent(
                event_id="evt_m3_sundial_malfoy_mocks_friends_distractor",
                movie_id="hp_movie_3",
                movie_number=3,
                scene_id="m3_scene_sundial_mockery",
                start_time=4980.0,
                end_time=4994.0,
                characters_present=["Draco Malfoy", "Crabbe", "Goyle"],
                primary_subject="Draco Malfoy",
                secondary_subjects=["Crabbe", "Goyle"],
                action="laughs and mocks Buckbeak execution through binoculars",
                target="Hagrid's hut",
                interaction_type="mockery",
                location="Sundial Hill / Stone Circle",
                visible_objects=["binoculars", "trees"],
                emotional_state="cruel_gleeful",
                camera_scale="MEDIUM",
                camera_motion="static",
                preceding_event=None,
                following_event=None,
                dialogue_ref="Look at him! Come to see the show?",
                visual_description="Malfoy laughs cruelly with Crabbe and Goyle behind the standing stones, watching Hagrid's hut with binoculars before Hermione arrives.",
                observable_claims=["Malfoy holds binoculars", "Malfoy laughs with friends"],
                unsupported_claims=[],
                confidence=0.94,
            ),
            MovieEvent(
                event_id="evt_m3_paddock_buckbeak_slashes_malfoy",
                movie_id="hp_movie_3",
                movie_number=3,
                scene_id="m3_scene_paddock_creatures_class",
                start_time=2290.0,
                end_time=2298.0,
                characters_present=["Buckbeak", "Draco Malfoy", "Rubeus Hagrid", "Harry Potter"],
                primary_subject="Buckbeak",
                secondary_subjects=["Draco Malfoy"],
                action="strikes Draco Malfoy with sharp talons",
                target="Draco Malfoy",
                interaction_type="combat_strike",
                location="Hagrid Paddock",
                visible_objects=["Buckbeak talons", "Draco Malfoy robes", "paddock fences"],
                emotional_state="angered_defensive",
                camera_scale="MEDIUM_FULL",
                camera_motion="action_tracking",
                preceding_event=None,
                following_event=None,
                dialogue_ref="It's killed me! It's killed me!",
                visual_description="Buckbeak rears up on hind legs and slashes Malfoy across the arm with talons; Malfoy collapses backward onto the ground howling in pain.",
                observable_claims=["Buckbeak rears up on hind legs", "Buckbeak slashes Malfoy arm", "Malfoy falls onto ground"],
                unsupported_claims=["Buckbeak intended to kill Draco Malfoy"],
                confidence=1.0,
            ),

            # =================================================================
            # MOVIE 1 ADDITIONAL CANONICAL EVENTS
            # =================================================================
            MovieEvent(
                event_id="evt_m1_quidditch_harry_catches_snitch",
                movie_id="hp_movie_1",
                movie_number=1,
                scene_id="m1_scene_quidditch_match",
                start_time=4680.0,
                end_time=4710.0,
                characters_present=["Harry Potter", "Lee Jordan", "Gryffindor Quidditch Team"],
                primary_subject="Harry Potter",
                secondary_subjects=[],
                action="catches the Golden Snitch on broom",
                target="Golden Snitch",
                interaction_type="sport_action",
                location="Hogwarts Quidditch Pitch",
                visible_objects=["Nimbus 2000 broom", "Golden Snitch", "scarlet robes"],
                emotional_state="triumphant",
                camera_scale="MEDIUM_CLOSE_UP",
                camera_motion="action_tracking",
                preceding_event=None,
                following_event=None,
                dialogue_ref="He's caught the Snitch! Harry Potter receives 150 points for catching the Snitch!",
                visual_description="Harry stands up on his Nimbus 2000, tumbles onto the grass, and coughs the gleaming Golden Snitch out into his hand, raising it high for the crowd.",
                observable_claims=["Harry holds Golden Snitch in hand", "Golden Snitch wings flutter", "Harry smiles holding the Snitch"],
                unsupported_claims=[],
                confidence=0.99,
            ),
            MovieEvent(
                event_id="evt_m1_sorting_harry_wears_hat",
                movie_id="hp_movie_1",
                movie_number=1,
                scene_id="m1_scene_sorting_ceremony",
                start_time=2450.0,
                end_time=2480.0,
                characters_present=["Harry Potter", "Minerva McGonagall", "Students"],
                primary_subject="Harry Potter",
                secondary_subjects=["Minerva McGonagall"],
                action="sits on wooden stool wearing the Sorting Hat",
                target="Sorting Hat",
                interaction_type="ceremony",
                location="Hogwarts Great Hall",
                visible_objects=["Sorting Hat", "wooden stool", "floating candles"],
                emotional_state="tense_hopeful",
                camera_scale="CLOSE_UP",
                camera_motion="static",
                preceding_event=None,
                following_event=None,
                dialogue_ref="Not Slytherin, eh? Are you sure? Well, if you're sure... better be... GRYFFINDOR!",
                visual_description="Harry sits upon the four-legged stool with the oversized Sorting Hat slipping down over his eyes, whispering silently under his breath.",
                observable_claims=["Harry wears Sorting Hat", "Sorting Hat face moves while speaking", "McGonagall stands beside stool"],
                unsupported_claims=["The Sorting Hat considered sending Harry to Slytherin to fulfill prophecy"],
                confidence=1.0,
            ),

            # =================================================================
            # MOVIE 2 ADDITIONAL CANONICAL EVENTS
            # =================================================================
            MovieEvent(
                event_id="evt_m2_chamber_harry_stabs_diary",
                movie_id="hp_movie_2",
                movie_number=2,
                scene_id="m2_scene_chamber_diary_destruction",
                start_time=8850.0,
                end_time=8880.0,
                characters_present=["Harry Potter", "Tom Riddle", "Ginny Weasley"],
                primary_subject="Harry Potter",
                secondary_subjects=["Tom Riddle"],
                action="stabs Tom Riddle's diary with basilisk fang",
                target="Tom Riddle's diary",
                interaction_type="combat_destruction",
                location="Chamber of Secrets",
                visible_objects=["Tom Riddle's diary", "basilisk fang", "black ink", "Slytherin statue"],
                emotional_state="resolute_furious",
                camera_scale="MEDIUM_CLOSE_UP",
                camera_motion="dynamic_push",
                preceding_event=None,
                following_event=None,
                dialogue_ref=None,
                visual_description="Harry grabs the jagged black Basilisk fang and plunges it straight through the black leather cover of Tom Riddle's diary; black ink geysers out as Riddle screams in blinding light.",
                observable_claims=["Harry stabs diary with basilisk fang", "Black ink spurts from diary pages", "Riddle screams as light pierces his chest"],
                unsupported_claims=[],
                confidence=1.0,
            ),

            # =================================================================
            # MOVIE 3 ADDITIONAL CANONICAL EVENTS
            # =================================================================
            MovieEvent(
                event_id="evt_m3_lake_harry_casts_patronum",
                movie_id="hp_movie_3",
                movie_number=3,
                scene_id="m3_scene_lake_patronus",
                start_time=7410.0,
                end_time=7440.0,
                characters_present=["Harry Potter", "Hermione Granger", "Sirius Black"],
                primary_subject="Harry Potter",
                secondary_subjects=[],
                action="casts Expecto Patronum across the Great Lake",
                target="Dementors",
                interaction_type="magical_casting",
                location="Hogwarts Great Lake shore",
                visible_objects=["wand", "silver stag patronus", "frozen lake"],
                emotional_state="fierce_focused",
                camera_scale="MEDIUM_WIDE",
                camera_motion="dolly_forward",
                preceding_event=None,
                following_event=None,
                dialogue_ref="EXPECTO PATRONUM!",
                visual_description="Harry stands at the water's edge in the forest, thrusts his wand forward with both hands, shouting the incantation as a colossal brilliant white silver stag erupts from his wand tip.",
                observable_claims=["Harry casts Expecto Patronum", "Blinding white light repels Dementors across lake", "Silver stag shape charges over the water"],
                unsupported_claims=[],
                confidence=1.0,
            ),

            # =================================================================
            # MOVIE 4: GOBLET OF FIRE (CANONICAL EVENTS & CHAIN)
            # Event Chain: Flees Dragon -> Summons Firebolt (Accio) -> Mounts Broom
            # =================================================================
            MovieEvent(
                event_id="evt_m4_first_task_harry_flees_dragon",
                movie_id="hp_movie_4",
                movie_number=4,
                scene_id="m4_scene_first_task_dragon_arena",
                start_time=3510.0,
                end_time=3535.0,
                characters_present=["Harry Potter", "Hungarian Horntail"],
                primary_subject="Harry Potter",
                secondary_subjects=["Hungarian Horntail"],
                action="flees Hungarian Horntail dragon across rocky arena",
                target="rock shelter",
                interaction_type="combat_evasion",
                location="Triwizard Arena",
                visible_objects=["rocks", "dragon chains", "Hungarian Horntail"],
                emotional_state="terrified_desperate",
                camera_scale="WIDE_SHOT",
                camera_motion="action_tracking",
                preceding_event=None,
                following_event="evt_m4_first_task_harry_summons_firebolt",
                dialogue_ref="Your wand, Harry! Your wand!",
                visual_description="Harry scrambles across the jagged boulders of the Triwizard arena as the Hungarian Horntail unleashes a torrent of fire, forcing Harry behind a rock outcrop.",
                observable_claims=["Harry runs from dragon", "Dragon breathes fire against rocks", "Harry cowers behind boulder"],
                unsupported_claims=[],
                confidence=0.98,
            ),
            # THE CORE OBSERVABLE EVENT (MOVIE 4 BENCHMARK):
            MovieEvent(
                event_id="evt_m4_first_task_harry_summons_firebolt",
                movie_id="hp_movie_4",
                movie_number=4,
                scene_id="m4_scene_first_task_accio_firebolt",
                start_time=3540.0,
                end_time=3565.0,
                characters_present=["Harry Potter"],
                primary_subject="Harry Potter",
                secondary_subjects=[],
                action="summons Firebolt broom with Accio spell",
                target="Firebolt broom",
                interaction_type="magical_summoning",
                location="Triwizard Arena",
                visible_objects=["wand", "Firebolt broom", "red Gryffindor robes"],
                emotional_state="focused_determined",
                camera_scale="MEDIUM_CLOSE_UP",
                camera_motion="dynamic_zoom",
                preceding_event="evt_m4_first_task_harry_flees_dragon",
                following_event="evt_m4_first_task_harry_mounts_firebolt",
                dialogue_ref="Accio Firebolt!",
                visual_description="Taking cover behind the boulder, Harry points his wand toward Hogwarts castle and shouts 'Accio Firebolt!'; seconds later, the sleek Firebolt broom flies at high speed through the sky and into his grasp.",
                observable_claims=["Harry points wand and shouts spell", "Firebolt broom flies over castle towers", "Harry catches the Firebolt handle"],
                unsupported_claims=["Harry learned Accio specifically to emulate James Potter"],
                confidence=1.0,
            ),
            MovieEvent(
                event_id="evt_m4_first_task_harry_mounts_firebolt",
                movie_id="hp_movie_4",
                movie_number=4,
                scene_id="m4_scene_first_task_flight",
                start_time=3568.0,
                end_time=3595.0,
                characters_present=["Harry Potter", "Hungarian Horntail"],
                primary_subject="Harry Potter",
                secondary_subjects=["Hungarian Horntail"],
                action="mounts Firebolt and soars into the sky",
                target="Hungarian Horntail",
                interaction_type="aerial_flight",
                location="Triwizard Arena",
                visible_objects=["Firebolt broom", "arena stands"],
                emotional_state="exhilarated",
                camera_scale="WIDE_SHOT",
                camera_motion="flyby",
                preceding_event="evt_m4_first_task_harry_summons_firebolt",
                following_event=None,
                dialogue_ref=None,
                visual_description="Harry swings his leg over the Firebolt and kicks off the rocks, rocketing into the vertical air while the Hungarian Horntail breaks its chain in pursuit.",
                observable_claims=["Harry mounts broom", "Harry accelerates upwards", "Dragon pursues into clouds"],
                unsupported_claims=[],
                confidence=0.98,
            ),
            MovieEvent(
                event_id="evt_m4_maze_harry_cedric_touch_cup",
                movie_id="hp_movie_4",
                movie_number=4,
                scene_id="m4_scene_maze_cup_grab",
                start_time=7140.0,
                end_time=7165.0,
                characters_present=["Harry Potter", "Cedric Diggory"],
                primary_subject="Harry Potter",
                secondary_subjects=["Cedric Diggory"],
                action="touches the Triwizard Cup with Cedric",
                target="Triwizard Cup",
                interaction_type="cooperative_action",
                location="Triwizard Maze",
                visible_objects=["Triwizard Cup", "glowing blue cup handles", "hedge walls"],
                emotional_state="exhausted_sportsmanlike",
                camera_scale="TWO_SHOT",
                camera_motion="crane_down",
                preceding_event=None,
                following_event=None,
                dialogue_ref="On three. One, two, three!",
                visual_description="Harry and Cedric reach out simultaneously and grasp the twin handles of the glowing blue Triwizard Cup, instantly triggering the Portkey swirl that transports them away.",
                observable_claims=["Harry and Cedric stand beside the cup", "Both boys touch the cup handles together", "Cup glows with blue portkey light"],
                unsupported_claims=["Cedric sensed that the cup was a trap"],
                confidence=1.0,
            ),
            MovieEvent(
                event_id="evt_m4_graveyard_voldemort_casts_crucio",
                movie_id="hp_movie_4",
                movie_number=4,
                scene_id="m4_scene_graveyard_torture",
                start_time=7615.0,
                end_time=7640.0,
                characters_present=["Lord Voldemort", "Harry Potter", "Death Eaters"],
                primary_subject="Lord Voldemort",
                secondary_subjects=["Harry Potter"],
                action="casts Crucio torture curse on Harry",
                target="Harry Potter",
                interaction_type="combat_torture",
                location="Little Hangleton Graveyard",
                visible_objects=["yew wand", "Riddle gravestone statue", "Death Eater circle"],
                emotional_state="cruel_triumphant",
                camera_scale="MEDIUM",
                camera_motion="slow_push",
                preceding_event=None,
                following_event=None,
                dialogue_ref="Crucio!",
                visual_description="Voldemort raises his pale bone-white wand and points it squarely at the bound, bleeding Harry Potter, shouting 'Crucio!' as red lightning convulses Harry in agonizing spasms.",
                observable_claims=["Voldemort raises wand", "Red curse beam strikes Harry", "Harry wriths on ground in agony"],
                unsupported_claims=[],
                confidence=1.0,
            ),
            MovieEvent(
                event_id="evt_m4_defense_moody_drinks_polyjuice_flask",
                movie_id="hp_movie_4",
                movie_number=4,
                scene_id="m4_scene_defense_classroom_flask",
                start_time=1980.0,
                end_time=2005.0,
                characters_present=["Mad-Eye Moody", "Students"],
                primary_subject="Mad-Eye Moody",
                secondary_subjects=[],
                action="drinks Polyjuice potion from silver hip flask",
                target="Polyjuice hip flask",
                interaction_type="lone_action",
                location="Defense Against the Dark Arts classroom",
                visible_objects=["silver hip flask", "magical eye", "walking staff"],
                emotional_state="secretive_agitated",
                camera_scale="CLOSE_UP",
                camera_motion="static",
                preceding_event=None,
                following_event=None,
                dialogue_ref=None,
                visual_description="Mad-Eye Moody (Barty Crouch Jr.) jerks open the metal cap of his curved silver hip flask and hastily takes several deep swigs, grimacing as his face twitches.",
                observable_claims=["Moody unscrews hip flask", "Moody drinks liquid from flask", "Moody grimaces as throat spasms"],
                unsupported_claims=["Moody is running low on boomslang skin"],
                confidence=0.99,
            ),
            # MOVIE 4 NEGATIVE DISTRACTOR (action mismatch: holds flask / stands without drinking)
            MovieEvent(
                event_id="evt_m4_defense_moody_holds_flask_standing_distractor",
                movie_id="hp_movie_4",
                movie_number=4,
                scene_id="m4_scene_defense_standing",
                start_time=1950.0,
                end_time=1970.0,
                characters_present=["Mad-Eye Moody"],
                primary_subject="Mad-Eye Moody",
                secondary_subjects=[],
                action="stands motionless holding silver flask against chalkboard",
                target="chalkboard",
                interaction_type="standing_idle",
                location="Defense Against the Dark Arts classroom",
                visible_objects=["silver hip flask", "chalkboard"],
                emotional_state="stern",
                camera_scale="MEDIUM",
                camera_motion="static",
                preceding_event=None,
                following_event=None,
                dialogue_ref="Who can tell me what curses are forbidden?",
                visual_description="Moody stands leaning against the blackboard with his closed silver hip flask resting against his chest, staring across the quiet classroom.",
                observable_claims=["Moody stands with flask", "Moody speaks to students"],
                unsupported_claims=[],
                confidence=0.92,
            ),

            # =================================================================
            # MOVIE 5: ORDER OF THE PHOENIX (CANONICAL EVENTS & CHAIN)
            # Event Chain: DA Assembly -> Casts Patronum -> Silver Stag Manifests
            # =================================================================
            MovieEvent(
                event_id="evt_m5_ror_da_training_assembly",
                movie_id="hp_movie_5",
                movie_number=5,
                scene_id="m5_scene_ror_assembly",
                start_time=4910.0,
                end_time=4924.0,
                characters_present=["Harry Potter", "Dumbledore's Army Students", "Hermione Granger", "Ron Weasley"],
                primary_subject="Harry Potter",
                secondary_subjects=["Dumbledore's Army Students"],
                action="addresses Dumbledore's Army students in Room of Requirement",
                target="Dumbledore's Army Students",
                interaction_type="instruction",
                location="Room of Requirement",
                visible_objects=["wands", "mirrors", "training dummies"],
                emotional_state="encouraging_leader",
                camera_scale="MEDIUM_WIDE",
                camera_motion="pan",
                preceding_event=None,
                following_event="evt_m5_ror_harry_casts_patronum",
                dialogue_ref="A full-bodied Patronus is the most difficult to produce...",
                visual_description="Harry walks among lines of practicing students in the mirror-lined Room of Requirement, instructing them on focusing on their happiest memory.",
                observable_claims=["Harry paces between students", "Students hold wands ready", "Mirrors reflect training room"],
                unsupported_claims=[],
                confidence=0.97,
            ),
            # THE CORE OBSERVABLE EVENT (MOVIE 5 BENCHMARK):
            MovieEvent(
                event_id="evt_m5_ror_harry_casts_patronum",
                movie_id="hp_movie_5",
                movie_number=5,
                scene_id="m5_scene_ror_patronus_cast",
                start_time=4925.0,
                end_time=4945.0,
                characters_present=["Harry Potter", "Dumbledore's Army Students"],
                primary_subject="Harry Potter",
                secondary_subjects=[],
                action="casts Expecto Patronum in Room of Requirement",
                target="Room of Requirement air",
                interaction_type="magical_casting",
                location="Room of Requirement",
                visible_objects=["wand", "silver patronus vapor", "mirrored walls"],
                emotional_state="radiant_focused",
                camera_scale="MEDIUM",
                camera_motion="arc",
                preceding_event="evt_m5_ror_da_training_assembly",
                following_event="evt_m5_ror_patronum_stag_manifests",
                dialogue_ref="Expecto Patronum.",
                visual_description="Harry closes his eyes for an instant, smiles with serene happiness, raises his wand with a firm circular flourish, and incants 'Expecto Patronum' as blinding silver light bursts from the tip.",
                observable_claims=["Harry raises wand in flourish", "Harry incants Expecto Patronum", "Luminous silver light emits from wand"],
                unsupported_claims=["Harry was thinking about the first time he kissed Cho"],
                confidence=1.0,
            ),
            MovieEvent(
                event_id="evt_m5_ror_patronum_stag_manifests",
                movie_id="hp_movie_5",
                movie_number=5,
                scene_id="m5_scene_ror_stag_flight",
                start_time=4948.0,
                end_time=4970.0,
                characters_present=["Harry Potter", "Dumbledore's Army Students"],
                primary_subject="Harry Potter",
                secondary_subjects=["Dumbledore's Army Students"],
                action="directs full silver stag patronus through room",
                target="silver stag patronus",
                interaction_type="magical_display",
                location="Room of Requirement",
                visible_objects=["silver stag patronus", "wand"],
                emotional_state="proud_joyful",
                camera_scale="WIDE_SHOT",
                camera_motion="tracking",
                preceding_event="evt_m5_ror_harry_casts_patronum",
                following_event=None,
                dialogue_ref="This is really advanced stuff, guys. You're doing so well.",
                visual_description="A radiant, translucent silver-white stag with grand antlers gallops through the vaulted air of the Room of Requirement, circling over the smiling students.",
                observable_claims=["Full-bodied silver stag patronus visible", "Stag gallops over students", "Students cheer and look up"],
                unsupported_claims=[],
                confidence=1.0,
            ),
            MovieEvent(
                event_id="evt_m5_atrium_dumbledore_voldemort_water_sphere",
                movie_id="hp_movie_5",
                movie_number=5,
                scene_id="m5_scene_atrium_duel",
                start_time=7115.0,
                end_time=7155.0,
                characters_present=["Albus Dumbledore", "Lord Voldemort", "Harry Potter"],
                primary_subject="Albus Dumbledore",
                secondary_subjects=["Lord Voldemort"],
                action="conjures giant water sphere encasing Voldemort at fountain",
                target="Lord Voldemort",
                interaction_type="magical_duel",
                location="Ministry of Magic Atrium",
                visible_objects=["Elder Wand", "Ministry fountain water", "golden statues"],
                emotional_state="commanding_calm",
                camera_scale="WIDE_SHOT",
                camera_motion="pan",
                preceding_event=None,
                following_event=None,
                dialogue_ref="It was foolish of you to come here tonight, Tom.",
                visual_description="Dumbledore waves the Elder Wand in wide sweeping circles, lifting tons of water out of the atrium fountain into a shimmering spherical vortex that traps Voldemort suspended in mid-air.",
                observable_claims=["Dumbledore sweeps wand", "Giant sphere of water encloses Voldemort", "Voldemort struggles inside water cocoon"],
                unsupported_claims=[],
                confidence=1.0,
            ),
            MovieEvent(
                event_id="evt_m5_dom_sirius_punches_malfoy",
                movie_id="hp_movie_5",
                movie_number=5,
                scene_id="m5_scene_dom_dais_combat",
                start_time=6918.0,
                end_time=6935.0,
                characters_present=["Sirius Black", "Lucius Malfoy", "Harry Potter"],
                primary_subject="Sirius Black",
                secondary_subjects=["Lucius Malfoy"],
                action="punches Lucius Malfoy squarely in the face",
                target="Lucius Malfoy",
                interaction_type="physical_strike",
                location="Department of Mysteries",
                visible_objects=["wand", "veiled stone archway", "dais steps"],
                emotional_state="furious_protective",
                camera_scale="TWO_SHOT",
                camera_motion="handheld_snap",
                preceding_event=None,
                following_event=None,
                dialogue_ref="Get away from my godson!",
                visual_description="Sirius Black dashes up onto the stone dais, roars 'Get away from my godson!', and throws a hard right punch knocking Lucius Malfoy backward off his feet.",
                observable_claims=["Sirius punches Lucius in the jaw", "Lucius stumbles backward", "Harry watches from dais"],
                unsupported_claims=[],
                confidence=1.0,
            ),
            # MOVIE 5 NEGATIVE DISTRACTOR (action mismatch: merely stands before fountain)
            MovieEvent(
                event_id="evt_m5_atrium_dumbledore_stands_fountain_distractor",
                movie_id="hp_movie_5",
                movie_number=5,
                scene_id="m5_scene_atrium_arrival",
                start_time=7080.0,
                end_time=7105.0,
                characters_present=["Albus Dumbledore", "Harry Potter"],
                primary_subject="Albus Dumbledore",
                secondary_subjects=["Harry Potter"],
                action="stands motionless before the golden fountain",
                target="fountain",
                interaction_type="standing_idle",
                location="Ministry of Magic Atrium",
                visible_objects=["Elder Wand", "golden fountain statues"],
                emotional_state="grave",
                camera_scale="MEDIUM_WIDE",
                camera_motion="static",
                preceding_event=None,
                following_event=None,
                dialogue_ref=None,
                visual_description="Dumbledore steps out of the green Floo fireplace and stands motionless on the green marble floor looking across at Harry.",
                observable_claims=["Dumbledore stands still", "Robes motionless"],
                unsupported_claims=[],
                confidence=0.91,
            ),

            # =================================================================
            # MOVIE 6: HALF-BLOOD PRINCE (CANONICAL EVENTS & CHAIN)
            # Event Chain: Drinks Felix Felicis -> Walks Out -> Approaches Slughorn
            # =================================================================
            MovieEvent(
                event_id="evt_m6_common_room_harry_drinks_felix_felicis",
                movie_id="hp_movie_6",
                movie_number=6,
                scene_id="m6_scene_common_room_felix_drink",
                start_time=6210.0,
                end_time=6235.0,
                characters_present=["Harry Potter", "Hermione Granger", "Ron Weasley"],
                primary_subject="Harry Potter",
                secondary_subjects=["Hermione Granger", "Ron Weasley"],
                action="drinks Felix Felicis potion from small vial",
                target="Felix Felicis vial",
                interaction_type="lone_ingestion",
                location="Gryffindor Common Room",
                visible_objects=["Felix Felicis vial", "glass stopper", "red armchairs"],
                emotional_state="delighted_confident",
                camera_scale="CLOSE_UP",
                camera_motion="slow_push",
                preceding_event=None,
                following_event="evt_m6_greenhouse_harry_approaches_slughorn",
                dialogue_ref="Well, how do you feel? - Excellent. Really excellent.",
                visual_description="Harry uncorks the tiny golden glass bottle, tips the liquid drops onto his tongue, and swallows the Felix Felicis potion, smiling with sudden boundless euphoria.",
                observable_claims=["Harry uncorks vial", "Harry drinks liquid from vial", "Harry grins with immense confidence"],
                unsupported_claims=["The luck potion immediately told Harry that Aragog was dead"],
                confidence=1.0,
            ),
            MovieEvent(
                event_id="evt_m6_greenhouse_harry_approaches_slughorn",
                movie_id="hp_movie_6",
                movie_number=6,
                scene_id="m6_scene_greenhouse_encounter",
                start_time=6288.0,
                end_time=6315.0,
                characters_present=["Harry Potter", "Horace Slughorn"],
                primary_subject="Harry Potter",
                secondary_subjects=["Horace Slughorn"],
                action="approaches and confronts Slughorn in greenhouse",
                target="Horace Slughorn",
                interaction_type="confrontation",
                location="Hogwarts Greenhouse",
                visible_objects=["Venomous Tentacula leaves", "greenhouse glass", "clipping shears"],
                emotional_state="cheerfully_brazen",
                camera_scale="TWO_SHOT",
                camera_motion="tracking",
                preceding_event="evt_m6_common_room_harry_drinks_felix_felicis",
                following_event=None,
                dialogue_ref="Merlin's beard, Harry! - Sorry, sir. I should've announced myself.",
                visual_description="High on liquid luck, Harry strides breezily into the dark greenhouse, cheerfully greeting a startled Slughorn who is poaching Tentacula leaves.",
                observable_claims=["Harry walks up to Slughorn", "Slughorn flinches dropping shears", "Harry smiles directly at Slughorn"],
                unsupported_claims=[],
                confidence=0.98,
            ),
            MovieEvent(
                event_id="evt_m6_cave_dumbledore_conjures_ring_of_fire",
                movie_id="hp_movie_6",
                movie_number=6,
                scene_id="m6_scene_cave_firestorm",
                start_time=7580.0,
                end_time=7620.0,
                characters_present=["Albus Dumbledore", "Harry Potter", "Inferi"],
                primary_subject="Albus Dumbledore",
                secondary_subjects=["Inferi", "Harry Potter"],
                action="conjures swirling ring of fire in Horcrux cave",
                target="Inferi",
                interaction_type="magical_clearing",
                location="Horcrux Cave",
                visible_objects=["Elder Wand", "ring of fire", "black island rock", "water basin"],
                emotional_state="majestic_resolute",
                camera_scale="WIDE_SHOT",
                camera_motion="crane_up",
                preceding_event=None,
                following_event=None,
                dialogue_ref=None,
                visual_description="Weakened but magnificent, Dumbledore stands atop the black island rock and spins the Elder Wand in a circle, generating a raging vortex of crimson fire that sweeps over the lake, immolating the climbing Inferi.",
                observable_claims=["Dumbledore brandishes wand overhead", "Massive circle of fire erupts around island", "Inferi recoil from flames into water"],
                unsupported_claims=[],
                confidence=1.0,
            ),
            MovieEvent(
                event_id="evt_m6_tower_snape_casts_avada_kedavra",
                movie_id="hp_movie_6",
                movie_number=6,
                scene_id="m6_scene_astronomy_tower_climax",
                start_time=8040.0,
                end_time=8065.0,
                characters_present=["Severus Snape", "Albus Dumbledore", "Draco Malfoy", "Death Eaters"],
                primary_subject="Severus Snape",
                secondary_subjects=["Albus Dumbledore"],
                action="casts Avada Kedavra killing Dumbledore on Astronomy Tower",
                target="Albus Dumbledore",
                interaction_type="execution_curse",
                location="Astronomy Tower",
                visible_objects=["wand", "green curse jet", "tower railing"],
                emotional_state="anguished_grim",
                camera_scale="CLOSE_UP",
                camera_motion="static",
                preceding_event=None,
                following_event=None,
                dialogue_ref="Severus... please. - Avada Kedavra.",
                visual_description="Snape steps forward into the moonlight, raises his wand directly at Dumbledore's chest, whispers 'Avada Kedavra', and a blinding green jet of light blasts Dumbledore backward over the tower rampart.",
                observable_claims=["Snape raises wand", "Snape speaks Avada Kedavra", "Green light strikes Dumbledore", "Dumbledore falls from tower"],
                unsupported_claims=["Dumbledore had secretly begged Snape to kill him months prior"],
                confidence=1.0,
            ),
            # MOVIE 6 NEGATIVE DISTRACTOR (action mismatch: holds goblet without drinking)
            MovieEvent(
                event_id="evt_m6_cave_dumbledore_holds_crystal_goblet_distractor",
                movie_id="hp_movie_6",
                movie_number=6,
                scene_id="m6_scene_cave_basin_pause",
                start_time=7380.0,
                end_time=7398.0,
                characters_present=["Albus Dumbledore", "Harry Potter"],
                primary_subject="Albus Dumbledore",
                secondary_subjects=["Harry Potter"],
                action="stands holding empty crystal goblet over glowing basin",
                target="crystal goblet",
                interaction_type="standing_idle",
                location="Horcrux Cave",
                visible_objects=["crystal goblet", "green glowing basin", "potion"],
                emotional_state="grim_hesitant",
                camera_scale="MEDIUM_CLOSE_UP",
                camera_motion="static",
                preceding_event=None,
                following_event=None,
                dialogue_ref="It has to be drunk. All of it.",
                visual_description="Dumbledore stands by the green-lit stone basin holding the crystal goblet motionless in his hand before taking any drink.",
                observable_claims=["Dumbledore holds goblet in hand", "Goblet remains unraised to lips"],
                unsupported_claims=[],
                confidence=0.94,
            ),

            # =================================================================
            # MOVIE 7: DEATHLY HALLOWS PART 1 (CANONICAL EVENTS & CHAIN)
            # Event Chain: Places Locket -> Ron Destroys Locket (Sword) -> Smoke Dissipates
            # =================================================================
            MovieEvent(
                event_id="evt_m7_forest_harry_places_locket_stone",
                movie_id="hp_movie_7",
                movie_number=7,
                scene_id="m7_scene_forest_locket_prep",
                start_time=5980.0,
                end_time=6005.0,
                characters_present=["Harry Potter", "Ron Weasley"],
                primary_subject="Harry Potter",
                secondary_subjects=["Ron Weasley"],
                action="places Slytherin Locket on flat stone",
                target="Slytherin Locket",
                interaction_type="preparation",
                location="Forest of Dean",
                visible_objects=["Slytherin Locket", "flat rock", "snow", "Sword of Gryffindor"],
                emotional_state="tense",
                camera_scale="MEDIUM_CLOSE_UP",
                camera_motion="tilt_down",
                preceding_event=None,
                following_event="evt_m7_forest_ron_destroys_locket_with_sword",
                dialogue_ref="I'll have to speak to it in order for it to open. When it does, don't hesitate.",
                visual_description="Harry lays the heavy gold Slytherin Locket Horcrux onto a flat rock in the snow, standing back while Ron grips the Sword of Gryffindor.",
                observable_claims=["Harry places locket on rock", "Locket rests on flat stone", "Ron holds sword nearby"],
                unsupported_claims=[],
                confidence=0.98,
            ),
            # THE CORE OBSERVABLE EVENT (MOVIE 7 BENCHMARK):
            MovieEvent(
                event_id="evt_m7_forest_ron_destroys_locket_with_sword",
                movie_id="hp_movie_7",
                movie_number=7,
                scene_id="m7_scene_forest_locket_strike",
                start_time=6015.0,
                end_time=6045.0,
                characters_present=["Ron Weasley", "Harry Potter"],
                primary_subject="Ron Weasley",
                secondary_subjects=["Harry Potter"],
                action="destroys Slytherin Locket with Sword of Gryffindor",
                target="Slytherin Locket",
                interaction_type="weapon_destruction",
                location="Forest of Dean",
                visible_objects=["Sword of Gryffindor", "Slytherin Locket", "Horcrux black smoke", "rubies"],
                emotional_state="furious_valiant",
                camera_scale="MEDIUM_CLOSE_UP",
                camera_motion="action_zoom",
                preceding_event="evt_m7_forest_harry_places_locket_stone",
                following_event="evt_m7_forest_locket_shatters_smoke_dissipates",
                dialogue_ref=None,
                visual_description="Defying the tormenting apparitions of Harry and Hermione, Ron screams, raises the Sword of Gryffindor with both hands high overhead, and drives the blade down with crushing force, splitting the Slytherin Locket in half.",
                observable_claims=["Ron raises sword high overhead", "Ron strikes sword blade into locket", "Locket glass shatters into pieces", "Black blood oozes from locket"],
                unsupported_claims=["Ron conquered the locket because he possessed pure Gryffindor blood"],
                confidence=1.0,
            ),
            MovieEvent(
                event_id="evt_m7_forest_locket_shatters_smoke_dissipates",
                movie_id="hp_movie_7",
                movie_number=7,
                scene_id="m7_scene_forest_locket_aftermath",
                start_time=6048.0,
                end_time=6070.0,
                characters_present=["Ron Weasley", "Harry Potter"],
                primary_subject="Ron Weasley",
                secondary_subjects=["Harry Potter"],
                action="breathes heavily over shattered smoking locket",
                target="shattered locket",
                interaction_type="aftermath",
                location="Forest of Dean",
                visible_objects=["shattered locket halves", "Sword of Gryffindor", "dissipating smoke"],
                emotional_state="sobbing_exhausted",
                camera_scale="MEDIUM",
                camera_motion="slow_pull_back",
                preceding_event="evt_m7_forest_ron_destroys_locket_with_sword",
                following_event=None,
                dialogue_ref="Just think, only three to go.",
                visual_description="The towering black smoke phantom dissolves with a dying shriek as Ron drops to his knees in the snow, panting in tears over the ruined locket halves.",
                observable_claims=["Smoke dissipates", "Ron drops to knees beside sword", "Locket lies broken in snow"],
                unsupported_claims=[],
                confidence=0.98,
            ),
            MovieEvent(
                event_id="evt_m7_godrics_bathilda_reveals_nagini",
                movie_id="hp_movie_7",
                movie_number=7,
                scene_id="m7_scene_bathilda_bedroom_attack",
                start_time=5450.0,
                end_time=5485.0,
                characters_present=["Bathilda Bagshot", "Nagini", "Harry Potter"],
                primary_subject="Bathilda Bagshot",
                secondary_subjects=["Nagini", "Harry Potter"],
                action="collapses and reveals Nagini bursting from body",
                target="Harry Potter",
                interaction_type="creature_reveal",
                location="Godric's Hollow",
                visible_objects=["Nagini snake", "bedroom wallpaper", "broken glass"],
                emotional_state="horrific",
                camera_scale="CLOSE_UP",
                camera_motion="whip_pan",
                preceding_event=None,
                following_event=None,
                dialogue_ref="Harry!",
                visual_description="In the dingy upstairs bedroom, Bathilda's neck unnaturally distorts, her elderly corpse slumps down, and the gargantuan snake Nagini erupts through her chest cavity, snapping its fangs at Harry.",
                observable_claims=["Corpse collapses", "Giant snake Nagini bursts forth", "Nagini strikes toward camera"],
                unsupported_claims=[],
                confidence=1.0,
            ),
            # MOVIE 7 NEGATIVE DISTRACTOR (action mismatch: stands holding sword without striking)
            MovieEvent(
                event_id="evt_m7_forest_ron_stands_holding_sword_distractor",
                movie_id="hp_movie_7",
                movie_number=7,
                scene_id="m7_scene_forest_frozen_hesitation",
                start_time=5970.0,
                end_time=5985.0,
                characters_present=["Ron Weasley", "Harry Potter"],
                primary_subject="Ron Weasley",
                secondary_subjects=["Harry Potter"],
                action="stands motionless holding Sword of Gryffindor looking frightened",
                target="Sword of Gryffindor",
                interaction_type="hesitation",
                location="Forest of Dean",
                visible_objects=["Sword of Gryffindor", "snowy trees"],
                emotional_state="terrified",
                camera_scale="MEDIUM",
                camera_motion="static",
                preceding_event=None,
                following_event=None,
                dialogue_ref="No, I can't. That thing affects me more than it affects you.",
                visual_description="Ron stands shaking in the cold snowy woods holding the sword loosely at his side, refusing to approach the locket.",
                observable_claims=["Ron stands with sword at side", "Sword does not strike"],
                unsupported_claims=[],
                confidence=0.93,
            ),

            # =================================================================
            # MOVIE 8 ADDITIONAL CANONICAL EVENTS & DISTRACTOR
            # =================================================================
            MovieEvent(
                event_id="evt_m8_courtyard_harry_voldemort_spell_clash",
                movie_id="hp_movie_8",
                movie_number=8,
                scene_id="m8_scene_courtyard_final_duel",
                start_time=6420.0,
                end_time=6450.0,
                characters_present=["Harry Potter", "Lord Voldemort"],
                primary_subject="Harry Potter",
                secondary_subjects=["Lord Voldemort"],
                action="casts Expelliarmus clashing spell beams against Voldemort",
                target="Lord Voldemort",
                interaction_type="magical_duel",
                location="Hogwarts Ruined Courtyard",
                visible_objects=["Elder Wand", "draco wand", "red beam", "green beam", "golden spark core"],
                emotional_state="fierce_finality",
                camera_scale="WIDE_SHOT",
                camera_motion="circular_tracking",
                preceding_event=None,
                following_event=None,
                dialogue_ref="Avada Kedavra! - Expelliarmus!",
                visual_description="In the smoking rubble of the courtyard, Harry and Voldemort cast simultaneously; the jet of green killing curse and red disarming charm lock together in a roaring central golden explosion of magic.",
                observable_claims=["Harry and Voldemort shoot wand beams", "Red and green beams collide", "Central energy core vibrates between them"],
                unsupported_claims=[],
                confidence=1.0,
            ),
            # MOVIE 8 NEGATIVE DISTRACTOR (action mismatch: stands holding hat without drawing sword)
            MovieEvent(
                event_id="evt_m8_courtyard_neville_stands_speechless_distractor",
                movie_id="hp_movie_8",
                movie_number=8,
                scene_id="m8_scene_courtyard_rubble_pause",
                start_time=6120.0,
                end_time=6138.0,
                characters_present=["Neville Longbottom", "Lord Voldemort"],
                primary_subject="Neville Longbottom",
                secondary_subjects=["Lord Voldemort"],
                action="stands silently clutching Sorting Hat in ruined courtyard",
                target="Sorting Hat",
                interaction_type="standing_idle",
                location="Hogwarts Ruined Courtyard",
                visible_objects=["Sorting Hat", "rubble"],
                emotional_state="battered_shocked",
                camera_scale="MEDIUM",
                camera_motion="static",
                preceding_event=None,
                following_event=None,
                dialogue_ref="Well, I must say, I'd hoped for better.",
                visual_description="Neville limps forward from the castle crowd holding the dusty Sorting Hat under his arm, standing silently while Voldemort laughs at him.",
                observable_claims=["Neville stands with hat", "Neville does not draw any weapon"],
                unsupported_claims=[],
                confidence=0.92,
            ),
            # =================================================================
            # MARAUDER'S MAP CANONICAL VISUAL EVENTS (Movie 3)
            # =================================================================
            MovieEvent(
                event_id="evt_m3_corridor_twins_activate_marauders_map",
                movie_id="hp_movie_3",
                movie_number=3,
                scene_id="m3_scene_corridor_map",
                start_time=3590.0,
                end_time=3625.0,
                characters_present=["Harry Potter", "George Weasley", "Fred Weasley"],
                primary_subject="George Weasley",
                secondary_subjects=["Harry Potter", "Fred Weasley"],
                action="taps blank parchment with wand as ink spreads and reveals the Marauder's Map",
                target="Marauder's Map",
                interaction_type="instruction",
                location="Hogwarts corridor",
                visible_objects=["Marauder's Map", "wand", "ink footprints", "parchment"],
                emotional_state="playful_conspiratorial",
                camera_scale="CLOSE_UP",
                camera_motion="pan",
                preceding_event=None,
                following_event="evt_m3_office_lupin_examines_marauders_map",
                dialogue_ref="George, if you will. I solemnly swear that I am up to no good.",
                visual_description="George taps the folded parchment with his wand, revealing animated ink script and tiny walking footprints of the Marauder's Map.",
                observable_claims=["George taps parchment with wand", "Ink spreads across paper", "Footprints appear"],
                unsupported_claims=[],
                confidence=1.0,
            ),
            MovieEvent(
                event_id="evt_m3_office_lupin_examines_marauders_map",
                movie_id="hp_movie_3",
                movie_number=3,
                scene_id="m3_scene_lupin_office_map",
                start_time=4625.0,
                end_time=4675.0,
                characters_present=["Remus Lupin", "Harry Potter"],
                primary_subject="Remus Lupin",
                secondary_subjects=["Harry Potter"],
                action="examines and folds the Marauder's Map parchment in office",
                target="Marauder's Map",
                interaction_type="dialogue",
                location="Defense Against the Dark Arts office",
                visible_objects=["Marauder's Map", "parchment", "office desk", "gramophone"],
                emotional_state="thoughtful_gentle",
                camera_scale="MEDIUM",
                camera_motion="static",
                preceding_event="evt_m3_night_corridor_harry_lumos_map",
                following_event=None,
                dialogue_ref="It looks as though it's a parchment designed to insult anyone who tries to read it.",
                visual_description="Lupin holds the Marauder's Map parchment, folding it gently and addressing Harry in his office.",
                observable_claims=["Lupin holds parchment map", "Lupin folds the map", "Harry stands listening"],
                unsupported_claims=[],
                confidence=1.0,
            ),
            MovieEvent(
                event_id="evt_m3_night_corridor_harry_lumos_map",
                movie_id="hp_movie_3",
                movie_number=3,
                scene_id="m3_scene_dark_corridor_map",
                start_time=4480.0,
                end_time=4525.0,
                characters_present=["Harry Potter"],
                primary_subject="Harry Potter",
                secondary_subjects=[],
                action="walks through dark Hogwarts corridor tracking footprints on the map with glowing wand",
                target="Marauder's Map",
                interaction_type="lone_action",
                location="Dark Hogwarts corridor",
                visible_objects=["Marauder's Map", "wand", "Lumos light", "parchment"],
                emotional_state="tense_curious",
                camera_scale="CLOSE_UP",
                camera_motion="tracking",
                preceding_event="evt_m3_corridor_twins_activate_marauders_map",
                following_event="evt_m3_office_lupin_examines_marauders_map",
                dialogue_ref="Lumos. Mischief managed. Nox.",
                visual_description="Harry creeps through the dark corridor holding the glowing wand tip over the unfolded Marauder's Map tracking footsteps.",
                observable_claims=["Harry holds glowing wand", "Harry examines map", "Footsteps walk on map"],
                unsupported_claims=[],
                confidence=1.0,
            ),
            # =================================================================
            # MIRROR OF ERISED & CHAMBER ENTRANCE CANONICAL EVENTS
            # =================================================================
            MovieEvent(
                event_id="evt_m1_classroom_mirror_of_erised_inscription",
                movie_id="hp_movie_1",
                movie_number=1,
                scene_id="m1_scene_mirror_erised",
                start_time=5535.0,
                end_time=5568.0,
                characters_present=["Harry Potter"],
                primary_subject="Harry Potter",
                secondary_subjects=[],
                action="examines carved gold inscription on the arch of the Mirror of Erised",
                target="Mirror of Erised",
                interaction_type="inspection",
                location="Abandoned classroom",
                visible_objects=["Mirror of Erised", "gold frame", "carved inscription", "brass lantern"],
                emotional_state="mesmerized",
                camera_scale="CLOSE_UP",
                camera_motion="pan",
                preceding_event=None,
                following_event=None,
                dialogue_ref="Erised stra ehru oyt ube cafru oyt on wohsi.",
                visual_description="Camera pans across the carved golden letters along the arch of the towering Mirror of Erised as Harry stares in wonder.",
                observable_claims=["Carved inscription visible on arch", "Harry gazes into reflective glass"],
                unsupported_claims=[],
                confidence=1.0,
            ),
            MovieEvent(
                event_id="evt_m2_chamber_harry_opens_parseltongue_entrance",
                movie_id="hp_movie_2",
                movie_number=2,
                scene_id="m2_scene_bathroom_parseltongue",
                start_time=6700.0,
                end_time=6740.0,
                characters_present=["Harry Potter", "Ron Weasley"],
                primary_subject="Harry Potter",
                secondary_subjects=["Ron Weasley"],
                action="speaks Parseltongue causing serpent tap to rotate and sink entrance to open",
                target="Chamber of Secrets entrance",
                interaction_type="spell_casting",
                location="Moaning Myrtle bathroom",
                visible_objects=["copper tap", "engraved snake", "circular sink basin", "pipe entrance"],
                emotional_state="focused_intense",
                camera_scale="MEDIUM_SHOT",
                camera_motion="tracking",
                preceding_event=None,
                following_event=None,
                dialogue_ref="Haa-sshay eth-sa-hay.",
                visual_description="Harry speaks Parseltongue at the snake-engraved faucet; the sink column separates and descends into the floor, opening the entrance pipe.",
                observable_claims=["Harry speaks Parseltongue", "Faucet glows and turns", "Sink descends revealing dark pipe"],
                unsupported_claims=[],
                confidence=1.0,
            ),
        ]

        for evt in events:
            self.add_event(evt)

        logger.info(f"Initialized MovieEventIndex with {len(self._events)} canonical events.")

    def search_candidates(self, query: MovieEventQuery) -> List[MovieEvent]:
        """
        Discovers candidate events that match broad character/subject or setting criteria,
        before detailed multi-attribute scoring and visual verification.
        """
        candidates: Set[str] = set()

        # Subject match filter
        if query.subject:
            sub_key = query.subject.lower()
            for indexed_sub, event_ids in self._subject_index.items():
                if sub_key in indexed_sub or indexed_sub in sub_key:
                    candidates.update(event_ids)

        # Action match filter
        if query.action:
            action_tokens = self._tokenize(query.action)
            for token in action_tokens:
                if token in self._action_index:
                    candidates.update(self._action_index[token])

        # Location filter
        if query.location:
            loc_tokens = self._tokenize(query.location)
            for token in loc_tokens:
                if token in self._location_index:
                    candidates.update(self._location_index[token])

        # Object filter
        if query.objects:
            for obj in query.objects:
                for token in self._tokenize(obj):
                    if token in self._object_index:
                        candidates.update(self._object_index[token])

        # If specific movie requested
        if query.movie_number and query.movie_number in self._movie_index:
            movie_events = self._movie_index[query.movie_number]
            candidates = candidates.intersection(movie_events) if candidates else set(movie_events)

        # Fallback to all events if candidate set is empty
        if not candidates:
            return list(self._events.values())

        return [self._events[eid] for eid in candidates if eid in self._events]
